Resources:
  SESIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: a.alhibshi@calo.app

  # ReceiptRuleSet:
  #   Type: AWS::SES::ReceiptRuleSet
  #   Properties:
  #     RuleSetName: SESRuleSet

  # SESEmailReceivedRule:
  #   Type: AWS::SES::ReceiptRule
  #   Properties:
  #     RuleSetName: SESRuleSet
  #     Rule:
  #       Name: SESReceiptRule
  #       Enabled: true
  #       Recipients: []
  #       Actions:
  #         - LambdaAction:
  #             FunctionArn: arn:aws:lambda:us-east-1:054700988317:function:calo-nutritionist-planner-dev-sendSaveEmail
  #             InvocationType: Event
  #         - StopAction:
  #             Scope: RuleSet

  # ReceiptRuleSet:
  #   Type: AWS::SES::ReceiptRuleSet
  #   Properties:
  #     RuleSetName: MyReceiptRuleSetName

  # ReceiptRule:
  #   Type: AWS::SES::ReceiptRule
  #   Properties:
  #     Rule:
  #       Actions:
  #         - LambdaAction:
  #             FunctionArn: arn:aws:lambda:us-east-1:054700988317:function:calo-nutritionist-planner-dev-sendSaveEmail
  #       Enabled: true
  #       Name: ReceiptRule
  #       Recipients: []
  #       ScanEnabled: true
  #     RuleSetName:
  #       Ref: ReceiptRuleSet
