Resources:
  SESIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: a.alhibshi@calo.app

  EmailIdentity2:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: m.mosfafa@calo.app