Resources:
  MealPictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-profile-picture-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
        BlockPublicPolicy: FALSE
        IgnorePublicAcls: FALSE
        RestrictPublicBuckets: FALSE

  MealPictureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: UserProfilePictureBucket
      PolicyDocument:
        Id: UserProfilePictureBucketPolicy
        Statement:
          - Sid: Allow-lambda-PutObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectAcl
            Resource:
              Fn::Sub:
                - arn:aws:s3:::${bucket}/*
                - bucket: 
                    Ref: UserProfilePictureBucket