createIngredient:
  handler: src/ingredients/createIngredient/handler.default
  events:
    - http:
        path: v1/ingredient/create
        method: post

getIngredients:
  handler: src/ingredients/getIngredients/handler.default
  events:
    - http:
        path: v1/ingredients
        method: get