createIngredient:
  handler: src/services/ingredients/createIngredient/handler.default
  events:
    - http:
        path: v1/ingredient
        method: post
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}

getIngredients:
  handler: src/services/ingredients/getIngredients/handler.default
  events:
    - http:
        path: v1/ingredients
        method: get
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        
searchIngredients:
  handler: src/services/ingredients/searchIngredients/handler.default
  events:
    - http:
        path: v1/ingredient/search
        method: get
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request:
          parameters:
            querystrings:
              name: true

updateIngredient:
  handler: src/services/ingredients/updateIngredient/handler.default
  events:
    - http:
        path: v1/ingredient/update
        method: put
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request:
          parameters:
            querystrings:
              id: true

deleteIngredient:
  handler: src/services/ingredients/deleteIngredient/handler.default
  events:
    - http:
        path: v1/ingredient/delete
        method: delete
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request: 
          parameters:
            querystrings:
              id: true