createComponent:
  handler: src/services/components/createComponent/handler.default
  events:
    - http:
        path: v1/component/create
        method: post
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}

getComponents:
  handler: src/services/components/getComponents/handler.default
  events:
    - http:
        path: v1/components
        method: get
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}

searchComponent:
  handler: src/services/components/searchComponents/handler.default
  events:
    - http:
        path: v1/component/search
        method: get
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request:
          parameters:
            querystrings:
              name: true

deleteComponent:
  handler: src/services/components/deleteComponent/handler.default
  events:
    - http:
        path: v1/component/delete
        method: delete
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request: 
          parameters:
            querystrings:
              id: true