createComponent:
  handler: src/services/components/createComponent/handler.default
  events:
    - http:
        path: v1/component
        method: post
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}

getComponents:
  handler: src/services/components/getComponents/handler.default
  events:
    - http:
        path: v1/components
        method: get
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request:
          parameters:
            querystrings:
              skip: true
              take: true

updateComponent:
  handler: src/services/components/updateComponent/handler.default
  events:
    - http:
        path: v1/component/update
        method: put
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request:
          parameters:
            querystrings:
              id: true

deleteComponent:
  handler: src/services/components/deleteComponent/handler.default
  events:
    - http:
        path: v1/component/delete
        method: delete
        cors: ${file(src/templates/cors.yml):${self:provider.stage}}
        request: 
          parameters:
            querystrings:
              id: true